### ISSUE TITLE
MoCA dataset evaluation like Table 3 in the paper

### ISSUE THREAD

**Issue by kimin-yun** [charigyang/motiongrouping#4]
First of all, congratulations on your paper being accepted in iccv 2021.
we develop the moving object region segmentation, so we test the MATNet and find your paper with MoCA dataset.

Since we want to compare the result on the MoCA dataset as Table 3, we find the "MoCA_eval.py" but it reads the csv file.
To run this code, we extract the MoCA_filtered, corresponding annotation PNG files, and optical flow, but we cannot make the csv file for MoCA_filtered.

Also, we test the eval.py through your pretrained model, your method records "0.6736" mean IoU.
But, we test the MATNet (from your google drive), it records "0.6379" mean IoU.
So, since the box annotation, we think that IoU in "eval.py" cannot reflect the performance on the MoCA dataset.

Anyway, we want to evaluate our result (binary mask image) on the MoCA dataset as Table 3, can you help me? (provide the csv files for MoCA filters or provide the evaluation code for Table 3) It will be very helpful for our research. 

report) There are several typos and errors.

tools/MoCA_crops.py 
- 115 line : dead_leaf_butterfly -> dead_leaf_butterfly_1
- When we read the negative coordinate of annotation (i.e., x, y in line 187), the anno_img makes error.
So, we add the conditions.
if x < 0: x = 0  
if y < 0: y = 0

**Comment by charigyang** [comment]
Hi,

Firstly, thanks for your interest in our paper.

You are correct -- eval.py cannot be used to fairly evaluate MoCA. This is because IoU between the prediction (mask) and ground truth (box) does not make sense. eval_moca.py addresses this by finding the box IoU instead (like detection tasks).

I have provided the csv that should be compatible with moca_filtered.py. I believe this should work, but if not, please let me know, and I'll look into it.

Thanks -- we'll also edit the errors accordingly.

[annotations.csv](https://github.com/charigyang/motiongrouping/files/6906546/annotations.csv)
